In [1]:
#import pandas as pd
import modin.pandas as pd
import gtfparse
from pathlib import Path

ModuleNotFoundError: No module named 'modin'

In [2]:
chm13t2t = Path("/mnt/group/references/genomic/homo_sapiens/sequences/chm13t2t/chm13.draft_v1.1.gene_annotation.v4.gff3.gz")
gencode = Path("/mnt/group/references/genomic/homo_sapiens/sequences/gencode_v38/gencode.v38.chr_patch_hapl_scaff.basic.annotation.gff3.gz")

In [ ]:
chm13t2t_anno = gtfparse.read_gtf(chm13t2t)

[parse_gtf(95)]: Reading in data in chunks
loading file:  11%|#1        | 1/9 [06:15<50:01, 375.14s/chunks]

In [6]:
chm13t2t_anno

In [12]:
chm13t2t_anno.df.head()

,seq_id,source,type,start,end,score,strand,phase,attributes
0,chr1,Liftoff,gene,11136,12457,.,-,.,gene_name=AL627309.3;source_gene=ENSG000002399...
1,chr1,Liftoff,transcript,11136,12457,.,-,.,gene_name=AL627309.3;source_gene=ENSG000002399...
2,chr1,Liftoff,exon,11136,11635,.,-,.,gene_name=AL627309.3;source_gene=ENSG000002399...
3,chr1,Liftoff,gene,11630,13433,.,+,.,gene_name=AP006222.2;source_gene=ENSG000002864...
4,chr1,Liftoff,transcript,11630,13433,.,+,.,gene_name=AP006222.2;source_gene=ENSG000002864...

In [7]:
gencode_anno = gffpd.read_gff3(gencode)

In [13]:
gencode_anno.df

,seq_id,source,type,start,end,score,strand,phase,attributes
0,chr1,HAVANA,gene,11869,14409,.,+,.,ID=ENSG00000223972.5;gene_id=ENSG00000223972.5...
1,chr1,HAVANA,transcript,11869,14409,.,+,.,ID=ENST00000456328.2;Parent=ENSG00000223972.5;...
2,chr1,HAVANA,exon,11869,12227,.,+,.,ID=exon:ENST00000456328.2:1;Parent=ENST0000045...
3,chr1,HAVANA,exon,12613,12721,.,+,.,ID=exon:ENST00000456328.2:2;Parent=ENST0000045...
4,chr1,HAVANA,exon,13221,14409,.,+,.,ID=exon:ENST00000456328.2:3;Parent=ENST0000045...
...,...,...,...,...,...,...,...,...,...
2043934,KI270744.1,ENSEMBL,transcript,51009,51114,.,-,.,ID=ENST00000616830.1;Parent=ENSG00000278625.1;...
2043935,KI270744.1,ENSEMBL,exon,51009,51114,.,-,.,ID=exon:ENST00000616830.1:1;Parent=ENST0000061...
2043936,KI270750.1,ENSEMBL,gene,148668,148843,.,+,.,ID=ENSG00000277374.1;gene_id=ENSG00000277374.1...
2043937,KI270750.1,ENSEMBL,transcript,148668,148843,.,+,.,ID=ENST00000612925.1;Parent=ENSG00000277374.1;...
2043938,KI270750.1,ENSEMBL,exon,148668,148843,.,+,.,ID=exon:ENST00000612925.1:1;Parent=ENST0000061...

In [7]:
gencode_df = pd.read_csv(gencode, delimiter="\t", nrows=100)

In [9]:
chm13t2t_df

                                                                               ##gff-version 3
chr1 Liftoff gene       11136  12457  . - .  gene_name=AL627309.3;source_gene=ENSG000002399...
             transcript 11136  12457  . - .  gene_name=AL627309.3;source_gene=ENSG000002399...
             exon       11136  11635  . - .  gene_name=AL627309.3;source_gene=ENSG000002399...
             gene       11630  13433  . + .  gene_name=AP006222.2;source_gene=ENSG000002864...
             transcript 11630  13433  . + .  gene_name=AP006222.2;source_gene=ENSG000002864...
...                                                                                        ...
     CAT     exon       371998 372122 . + .  source_transcript=ENST00000618181.4;source_tra...
             CDS        371998 372122 . + 2  source_transcript=ENST00000618181.4;source_tra...
             exon       371998 372122 . + .  source_transcript=ENST00000618323.4;source_tra...
                                          .  source_transcript=ENST00000618779.4;source_tra...
             CDS        371998 372122 . + 2  source_transcript=ENST00000618779.4;source_tra...

[1000 rows x 1 columns]